source 'https://rubygems.org'

gem 'rails', '3.2.14'
gem 'devise', '2.2.3'
gem 'haml', '4.0.0'
gem 'pg', '0.12.2'
gem 'geocoder'

gem 'rmagick'
gem 'mini_magick'
gem 'carrierwave'
gem 'fog', '1.3.1'

gem 'resque'
gem 'resque_mailer'

gem 'whenever', :require => false
gem 'mailboxer'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'